name: prenotalo

## docker compose up --service-ports

services:
  frontend:
    build:
      context: ./frontend
    # network_mode: host
    # networks:
    #   prenotalo:
    #     ipv4_address: 10.234.0.1
    ports:
      - 80:80

  event:
    build:
      context: ./services/event
    # network_mode: host
    ports:
      - 8001:8080
    user: 1000:1000

  notify:
    build:
      context: ./services/notify
    # network_mode: host
    ports:
      - 8002:8080
    user: 1000:1000

  pay:
    build:
      context: ./services/pay
    # network_mode: host
    ports:
      - 8003:8080
    user: 1000:1000

  survey:
    build:
      context: ./services/survey
    # network_mode: host
    ports:
      - 8004:8080
    user: 1000:1000

  user:
    build:
      context: ./services/user
    # network_mode: host
    ports:
      - 8005:8080
    user: 1000:1000

  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password

      MARIADB_DATABASE: prenotalo
      MARIADB_USER: prenotalo
      MARIADB_PASSWORD: password
    # network_mode: host
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
