name: prenotalo

## docker compose up --service-ports

services:
  frontend:
    build:
      context: ./frontend
    networks:
      prenotalo:
        ipv4_address: 10.234.0.1
    ports:
      - 80:80

  event:
    build:
      context: ./services/event
    networks:
      prenotalo:
        ipv4_address: 10.234.0.3
    volumes:
      - srv-data:/data

  organization:
    build:
      context: ./services/organization
    networks:
      prenotalo:
        ipv4_address: 10.234.0.4

  pay:
    build:
      context: ./services/pay
    networks:
      prenotalo:
        ipv4_address: 10.234.0.5
    volumes:
      - srv-data:/data

  reservations:
    build:
      context: ./services/reservations
    networks:
      prenotalo:
        ipv4_address: 10.234.0.6
    volumes:
      - srv-data:/data

  user:
    build:
      context: ./services/user
    networks:
      prenotalo:
        ipv4_address: 10.234.0.7

  curl:
    image: curlimages/curl
    tty: true # docker run -t
    stdin_open: true # docker run -i
    entrypoint: /bin/sh # Get a shell
    networks:
      prenotalo:
        ipv4_address: 10.234.0.10

  # database:
  #   image: mariadb
  #   environment:
  #     MARIADB_ROOT_PASSWORD: password
  #     MARIADB_DATABASE: prenotalo
  #     MARIADB_USER: prenotalo
  #     MARIADB_PASSWORD: password
  #   # network_mode: host
  #   networks:
  #     prenotalo:
  #       ipv4_address: 10.234.0.2
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db-data:/var/lib/mysql

networks:
  prenotalo:
    driver: bridge
    ipam:
      config:
        - subnet: 10.234.0.0/28
          gateway: 10.234.0.14

volumes:
  # db-data:
  srv-data:
